/* ALEX NEWS TODAY — dados do dia. Este é o ÚNICO arquivo que a tarefa diária reescreve. */
window.ANT_DATA = {
  date: "24/06/2026",
  quote: {
    pt:'"O sucesso é a soma de pequenos esforços repetidos dia após dia." — Robert Collier',
    it:'"Il successo è la somma di piccoli sforzi ripetuti giorno dopo giorno." — Robert Collier',
    en:'"Success is the sum of small efforts repeated day in and day out." — Robert Collier',
    fr:'"Le succès est la somme de petits efforts répétés jour après jour." — Robert Collier',
    de:'"Erfolg ist die Summe kleiner Anstrengungen, die Tag für Tag wiederholt werden." — Robert Collier',
    es:'"El éxito es la suma de pequeños esfuerzos repetidos día tras día." — Robert Collier'
  },
  hero: {
    url:"https://www.espn.com/soccer/story/_/id/49162646/world-cup-2026-today-blog-24-06-2026-live-updates-news-fixtures-schedule-results-england-ghana-draw-scotland",
    img:"https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=1200&q=75", src:"ESPN",
    t:{pt:"Copa 2026: Brasil x Escócia esta noite em Miami — Verdeamarelo busca liderança do Grupo C",it:"Mondiali 2026: Brasile-Scozia stanotte a Miami — I verdeoro puntano al primo posto nel Gruppo C",en:"World Cup 2026: Brazil vs Scotland tonight in Miami — Selecão seeks Group C top spot",fr:"Mondial 2026: Brésil-Écosse ce soir à Miami — La Seleção vise la tête du Groupe C",de:"WM 2026: Brasilien vs. Schottland heute Nacht in Miami — Seleção will Gruppenführung",es:"Mundial 2026: Brasil vs Escocia esta noche en Miami — La Seleção busca liderar el Grupo C"},
    s:{pt:"Brasil e Marrocos lideram Grupo C com 4 pts. Escócia (3 pts) precisa de resultado para avançar inédita às oitavas. Rayan deve ser titular.",it:"Brasile e Marocco guidano il Gruppo C con 4 punti. Scozia (3 pts) deve vincere per passare per la prima volta agli ottavi. Rayan favorito.",en:"Brazil and Morocco lead Group C on 4 pts. Scotland (3 pts) need a result to reach the knockouts for the first time. Rayan tipped to start.",fr:"Brésil et Maroc mènent le Groupe C à 4 pts. Écosse (3 pts) doit gagner pour atteindre les huitièmes pour la première fois.",de:"Brasilien und Marokko führen Gruppe C mit 4 Pkt. Schottland (3 Pkt.) braucht Ergebnis für historisches Achtelfinale. Rayan als Starter erwartet.",es:"Brasil y Marruecos lideran Grupo C con 4 pts. Escocia (3 pts) necesita ganar para llegar por primera vez a octavos. Se espera a Rayan."}
  },
  sections: [
   {key:"gossip",icon:"💎",title:{pt:"Gossip",it:"Gossip",en:"Gossip",fr:"People",de:"Klatsch",es:"Gossip"},items:[
     {url:"https://www.purepeople.com.br/arquivo/noticias/2026",img:"https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=600&q=70",src:"Purepeople",
      t:{pt:"Virgínia Fonseca rouba cena antes do jogo do Brasil na Copa 2026",it:"Virgínia Fonseca ruba la scena prima della partita del Brasile ai Mondiali 2026",en:"Virgínia Fonseca steals the spotlight ahead of Brazil World Cup game",fr:"Virgínia Fonseca vole la vedette avant le match du Brésil en Coupe du Monde",de:"Virgínia Fonseca stiehlt vor Brasiliens WM-Spiel die Show",es:"Virgínia Fonseca acapara los focos antes del partido de Brasil en el Mundial"},
      s:{pt:"Influenciadora apostou em look vibrante e agitou as redes antes do duelo Brasil x Escócia.",it:"L influencer ha scelto un look vibrante, scatenando i social prima di Brasile-Scozia.",en:"The influencer picked a vibrant look, buzzing social media before Brazil vs Scotland.",fr:"L influenceuse a misé sur un look vibrant, animant les réseaux avant Brésil-Écosse.",de:"Die Influencerin wählte leuchtenden Look und brachte soziale Netzwerke vor Brasilien-Schottland in Aufruhr.",es:"La influencer apostó por un look vibrante y agitó las redes antes del duelo Brasil-Escocia."}},
     {url:"https://www.purepeople.com.br/arquivo/noticias/2026",img:"https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=600&q=70",src:"Purepeople",
      t:{pt:"Nego Di condenado a mais de 14 anos de prisão por lavagem de dinheiro",it:"Nego Di condannato a oltre 14 anni di carcere per riciclaggio di denaro",en:"Nego Di sentenced to over 14 years in prison for money laundering",fr:"Nego Di condamné à plus de 14 ans de prison pour blanchiment d argent",de:"Nego Di zu mehr als 14 Jahren Gefängnis wegen Geldwäsche verurteilt",es:"Nego Di condenado a más de 14 años de prisión por lavado de dinero"},
      s:{pt:"O influenciador gaúcho foi condenado após investigação sobre fraudes financeiras milionárias.",it:"L influencer del Rio Grande do Sul è stato condannato per frodi finanziarie milionarie.",en:"The Rio Grande do Sul influencer was convicted following a multimillion-dollar financial fraud investigation.",fr:"L influenceur a été condamné après une enquête sur des fraudes financières de plusieurs millions.",de:"Der Influencer wurde nach Ermittlungen wegen millionenschwerer Finanzbetrug verurteilt.",es:"El influencer fue condenado tras una investigación sobre fraudes financieros millonarios."}}
   ]},
   {key:"imoveis",icon:"🏛️",title:{pt:"Imóveis de Alto Padrão",it:"Immobili di Lusso",en:"Luxury Real Estate",fr:"Immobilier de Luxe",de:"Luxusimmobilien",es:"Inmuebles de Lujo"},items:[
     {url:"https://visao.pt/opiniao/ponto-de-vista/2025-12-10-as-tendencias-do-mercado-imobiliario-de-luxo-em-2026/",img:"https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=600&q=70",src:"Visão",
      t:{pt:"Quiet Luxury domina o mercado imobiliário de alto padrão em 2026",it:"Il Quiet Luxury domina il mercato immobiliare di lusso nel 2026",en:"Quiet Luxury dominates the high-end real estate market in 2026",fr:"Le Quiet Luxury domine l immobilier haut de gamme en 2026",de:"Quiet Luxury dominiert den Hochpreisimmobilienmarkt 2026",es:"El Quiet Luxury domina el mercado inmobiliario de alto nivel en 2026"},
      s:{pt:"Compradores de alto padrão priorizam bem-estar, privacidade, tecnologia integrada e sustentabilidade.",it:"I compratori di alto livello privilegiano benessere, privacy, tecnologia integrata e sostenibilità.",en:"High-end buyers prioritize wellness, privacy, integrated technology and sustainability.",fr:"Les acheteurs haut de gamme privilégient bien-être, intimité, technologie intégrée et durabilité.",de:"Hochpreiskäufer priorisieren Wellness, Privatsphäre, integrierte Technologie und Nachhaltigkeit.",es:"Los compradores de alto nivel priorizan bienestar, privacidad, tecnología integrada y sostenibilidad."}},
     {url:"https://blog.colmeia.com.br/o-futuro-do-mercado-imobiliario-de-luxo-2026/",img:"https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=600&q=70",src:"Colmeia",
      t:{pt:"IA transforma a jornada de compra de imóveis de luxo no Brasil",it:"L IA trasforma il percorso di acquisto degli immobili di lusso in Brasile",en:"AI transforms the luxury property buying journey in Brazil",fr:"L IA transforme le parcours d achat immobilier de luxe au Brésil",de:"KI verändert den Kaufprozess für Luxusimmobilien in Brasilien",es:"La IA transforma el proceso de compra de inmuebles de lujo en Brasil"},
      s:{pt:"Plataformas como QuintoAndar integram IA em cada etapa: busca, visita, negociação e contrato.",it:"Piattaforme come QuintoAndar integrano l IA in ogni fase: ricerca, visita, trattativa e contratto.",en:"Platforms like QuintoAndar embed AI at every step: search, visit, negotiation and contract.",fr:"Des plateformes comme QuintoAndar intègrent l IA à chaque étape: recherche, visite, négociation, contrat.",de:"Plattformen wie QuintoAndar integrieren KI in jeden Schritt: Suche, Besichtigung, Verhandlung, Vertrag.",es:"Plataformas como QuintoAndar integran IA en cada paso: búsqueda, visita, negociación y contrato."}},
     {url:"https://kalangoatomico.com.br/noticias/as-principais-tendencias-do-mercado-imobiliario-de-luxo-em-2026-the-mercury-news/192948/",img:"https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=600&q=70",src:"Mercury News",
      t:{pt:"Nova geração de herdeiros rejuvenece o perfil do comprador de luxo mundial",it:"La nuova generazione di eredi ringiovanisce il profilo del compratore di lusso mondiale",en:"New generation of heirs rejuvenates the luxury buyer profile worldwide",fr:"La nouvelle génération d héritiers rajeunit le profil de l acheteur de luxe mondial",de:"Neue Erbengeneration verjüngt das Profil des Luxuskäufers weltweit",es:"Nueva generación de herederos rejuvenece el perfil del comprador de lujo mundial"},
      s:{pt:"Transferência de US$ 6 trilhões em patrimônio cria onda de jovens compradores de alto padrão.",it:"Il trasferimento di 6.000 miliardi di patrimonio crea un onda di giovani acquirenti di lusso.",en:"A US$6 trillion wealth transfer is creating a wave of young high-end property buyers.",fr:"Un transfert de 6 000 Md$ crée une vague de jeunes acheteurs haut de gamme.",de:"Ein 6-Bio.-$-Vermögenstransfer schafft eine Welle junger Luxuskäufer.",es:"Una transferencia de US$ 6 billones crea ola de jóvenes compradores de lujo."}}
   ]},
   {key:"brasil",icon:"🇧🇷",title:{pt:"Brasil",it:"Brasile",en:"Brazil",fr:"Brésil",de:"Brasilien",es:"Brasil"},items:[
     {url:"https://agenciabrasil.ebc.com.br/economia",img:"https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?w=600&q=70",src:"Agência Brasil",
      t:{pt:"Governo cria cota com imposto zero para importar elétricos desmontados a partir de julho",it:"Il governo crea una quota a imposta zero per importare auto elettriche smontate da luglio",en:"Government creates zero-tax quota to import knocked-down EVs from July",fr:"Le gouvernement crée un quota sans taxe pour importer des VE en kit à partir de juillet",de:"Regierung schafft Nullsteuerquote für CKD-Elektroautos ab Juli",es:"El gobierno crea cuota con impuesto cero para importar eléctricos desmontados desde julio"},
      s:{pt:"Camex aprova cota de US$ 463 mi em importações CKD e SKD por seis meses. Tarifa geral mantida.",it:"La Camex approva quota da 463 milioni per importazioni CKD e SKD per sei mesi. Tariffa generale mantenuta.",en:"Camex approves US$463m CKD and SKD import quota for six months. General tariff kept.",fr:"La Camex approuve un quota de 463 M$ pour importations CKD et SKD six mois. Tarif général maintenu.",de:"Camex genehmigt 463-Mio.-$-CKD-und-SKD-Importquote für sechs Monate. Allgemeiner Tarif bleibt.",es:"Camex aprueba cuota de US$ 463 mill. para importaciones CKD y SKD por seis meses. Tarifa general se mantiene."}},
     {url:"https://www.infomoney.com.br/economia/",img:"https://images.unsplash.com/photo-1565514020179-026b92b2d70b?w=600&q=70",src:"InfoMoney",
      t:{pt:"FMI: economia do Brasil permanece resiliente e crescimento deve se recuperar em 2026",it:"FMI: l economia del Brasile rimane resiliente e la crescita si riprenderà nel 2026",en:"IMF: Brazil economy stays resilient and growth set to recover in 2026",fr:"FMI: l économie brésilienne reste résiliente et la croissance devrait se redresser en 2026",de:"IWF: Brasiliens Wirtschaft bleibt resilient, Wachstum erholt sich 2026",es:"FMI: la economía de Brasil sigue resiliente y el crecimiento se recuperará en 2026"},
      s:{pt:"PIB estimado em 1,85% para 2026. Boletim Focus aponta Selic em 12,5% e inflação acima de 4,5%.",it:"PIL stimato all 1,85% per il 2026. Focus: Selic al 12,5% e inflazione sopra il 4,5%.",en:"GDP estimated at 1.85% for 2026. Focus Bulletin: Selic at 12.5%, inflation above 4.5%.",fr:"PIB estimé à 1,85% pour 2026. Bulletin Focus: Selic à 12,5%, inflation au-dessus de 4,5%.",de:"BIP für 2026 auf 1,85% geschätzt. Focus-Bericht: Selic bei 12,5%, Inflation über 4,5%.",es:"PIB estimado en 1,85% para 2026. Boletín Focus: Selic en 12,5%, inflación por encima de 4,5%."}}
   ]},
   {key:"mundo",icon:"🌍",title:{pt:"Itália e Mundo",it:"Italia e Mondo",en:"Italy and World",fr:"Italie et Monde",de:"Italien und Welt",es:"Italia y Mundo"},items:[
     {url:"https://www.cbsnews.com/live-updates/iran-us-war-trump-nuclear-sites-strait-of-hormuz/",img:"https://images.unsplash.com/photo-1523496922380-91d5afba98a3?w=600&q=70",src:"CBS News",
      t:{pt:"Trump diz que Irã aceitou inspeções nucleares; Teerã nega o acordo",it:"Trump afferma che l Iran ha accettato ispezioni nucleari; Teheran smentisce",en:"Trump says Iran agreed to nuclear inspections; Tehran denies the deal",fr:"Trump affirme que l Iran a accepté des inspections nucléaires; Téhéran dément",de:"Trump: Iran stimmte Nuklearinspektionen zu; Teheran dementiert",es:"Trump dice que Irán aceptó inspecciones nucleares; Teherán desmiente el acuerdo"},
      s:{pt:"Congresso dos EUA aprovou resolução para retirar forças americanas do conflito com o Irã.",it:"Il Congresso USA ha approvato una risoluzione per ritirare le forze americane dal conflitto con l Iran.",en:"US Congress passed a resolution directing withdrawal of American forces from the Iran conflict.",fr:"Le Congrès a voté une résolution pour retirer les forces américaines du conflit avec l Iran.",de:"US-Kongress verabschiedete Resolution zum Rückzug amerikanischer Streitkräfte aus Iran-Konflikt.",es:"El Congreso de EE.UU. aprobó resolución para retirar fuerzas americanas del conflicto con Irán."}},
     {url:"https://euronews.com/",img:"https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600&q=70",src:"Euronews",
      t:{pt:"França sofre onda de calor extremo com temperaturas recordes históricas",it:"La Francia subisce una ondata di caldo estremo con temperature da record storico",en:"France hit by extreme heatwave with historic record temperatures",fr:"La France frappée par une canicule extrême avec des températures records historiques",de:"Frankreich von extremer Hitzewelle mit historischen Rekordtemperaturen getroffen",es:"Francia sufre ola de calor extremo con temperaturas récord históricas"},
      s:{pt:"A maioria da população francesa está exposta ao calor extremo até o fim da semana.",it:"La maggior parte della popolazione francese è esposta al caldo estremo fino alla fine della settimana.",en:"Most of the French population is exposed to extreme heat expected to last until at least end of week.",fr:"La majorité de la population française est exposée à la chaleur extrême jusqu à la fin de la semaine.",de:"Der Großteil der französischen Bevölkerung ist bis Ende der Woche extremer Hitze ausgesetzt.",es:"La mayor parte de la población francesa está expuesta al calor extremo hasta al menos el fin de semana."}}
   ]},
   {key:"tech",icon:"💻",title:{pt:"Tecnologia",it:"Tecnologia",en:"Technology",fr:"Technologie",de:"Technologie",es:"Tecnología"},items:[
     {url:"https://www.alura.com.br/artigos/mercado-de-ia",img:"https://images.unsplash.com/photo-1677442136019-21780ecad995?w=600&q=70",src:"Alura",
      t:{pt:"Agentes de IA autônomos: a maior virada tecnológica do 2° semestre de 2026",it:"Agenti IA autonomi: la svolta tecnologica più grande del 2° semestre 2026",en:"Autonomous AI agents: the biggest tech shift of the second half of 2026",fr:"Agents IA autonomes: la plus grande rupture technologique du 2e semestre 2026",de:"Autonome KI-Agenten: größter Technologiewandel der zweiten Jahreshälfte 2026",es:"Agentes de IA autónomos: el mayor giro tecnológico del segundo semestre de 2026"},
      s:{pt:"IA deixa de ser assistente e passa a executar tarefas completas com menor intervenção humana.",it:"L IA smette di essere un assistente e inizia a eseguire compiti completi con minor intervento umano.",en:"AI is moving beyond assistant to executing full tasks with minimal human intervention.",fr:"L IA passe de l assistant à l exécutant de tâches complètes avec moins d intervention humaine.",de:"KI wechselt von Assistent zu eigenständigem Aufgabenausführer mit minimaler menschlicher Eingriffe.",es:"La IA pasa de asistente a ejecutora de tareas completas con mínima intervención humana."}},
     {url:"https://news.microsoft.com/source/latam/features/noticias-da-microsoft/o-que-vem-por-ai-na-ia-7-tendencias-para-ficar-de-olho-em-2026/?lang=pt-br",img:"https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=600&q=70",src:"Microsoft",
      t:{pt:"Mercado global de IA projetado em US$ 4,8 trilhões até 2033, diz ONU",it:"Mercato globale dell IA proiettato a 4.800 miliardi entro il 2033, dice l ONU",en:"Global AI market projected at US$ 4.8 trillion by 2033 says UN",fr:"Le marché mondial de l IA projeté à 4 800 Md$ d ici 2033 selon l ONU",de:"Globaler KI-Markt bis 2033 auf 4,8 Billionen USD projiziert laut UN",es:"El mercado global de IA proyectado en US$ 4,8 billones para 2033 dice la ONU"},
      s:{pt:"A IA consolida-se como infraestrutura invisível da economia global, superando a fase de deslumbramento.",it:"L IA si consolida come infrastruttura invisibile dell economia globale, superando la fase di entusiasmo.",en:"AI cements itself as the invisible infrastructure of the global economy, moving past the hype phase.",fr:"L IA s impose comme l infrastructure invisible de l économie mondiale, dépassant la phase d engouement.",de:"KI festigt sich als unsichtbare Infrastruktur der Weltwirtschaft und überschreitet die Hype-Phase.",es:"La IA se consolida como infraestructura invisible de la economía global, superando la fase de entusiasmo."}}
   ]},
   {key:"moda",icon:"👗",title:{pt:"Moda",it:"Moda",en:"Fashion",fr:"Mode",de:"Mode",es:"Moda"},items:[
     {url:"https://elle.com.br/moda/6-tendencias-para-o-verao-2026",img:"https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=70",src:"ELLE Brasil",
      t:{pt:"Guava Pink é a cor da vez: verão 2026 aposta em vibrância e leveza",it:"Il Guava Pink è il colore del momento: l estate 2026 punta su vibrazione e leggerezza",en:"Guava Pink is the colour of the moment: summer 2026 bets on vibrancy and lightness",fr:"Le rose goyave est la couleur du moment: l été 2026 mise sur la vibrance et la légèreté",de:"Guava Pink ist die Farbe des Moments: Sommer 2026 setzt auf Lebendigkeit und Leichtigkeit",es:"El Guava Pink es el color del momento: el verano 2026 apuesta por vibración y ligereza"},
      s:{pt:"Pastéis (baby pink, baby blue, amarelo manteiga) e franjas são as apostas fortes do verão.",it:"I pastelli (baby pink, baby blue, giallo burro) e le frange sono le scommesse forti dell estate.",en:"Pastels (baby pink, baby blue, butter yellow) and fringe are the season strong bets.",fr:"Les pastels (baby pink, baby blue, jaune beurre) et les franges sont les paris forts de la saison.",de:"Pastelltöne (Baby Pink, Baby Blue, Buttergelb) und Fransen sind die starken Saisonwetten.",es:"Los pasteles (baby pink, baby blue, amarillo mantequilla) y los flecos son las apuestas fuertes."}},
     {url:"https://www.terra.com.br/vida-e-estilo/autocuidado/moda/o-verao-2026-vai-ser-leve-veja-as-tendencias-que-dominam,e44adf1af10fa06040661d4636a05880t6wtoudm.html",img:"https://images.unsplash.com/photo-1445205170230-053b83016050?w=600&q=70",src:"Terra",
      t:{pt:"O verão 2026 vai ser leve: sapatilhas trançadas e sandálias thong são tendência",it:"L estate 2026 sarà leggera: ballerine intrecciate e sandali thong sono di tendenza",en:"Summer 2026 goes light: braided flats and thong sandals are the trend",fr:"L été 2026 sera léger: ballerines tressées et sandales thong sont tendance",de:"Sommer 2026 wird leicht: geflochtene Ballerinas und Thong-Sandalen sind Trend",es:"El verano 2026 será ligero: bailarinas trenzadas y sandalias thong son tendencia"},
      s:{pt:"Chapéu volta como peça-chave e franjas invadem bolsas e calçados neste verão minimalista.",it:"Il cappello torna protagonista e le frange invadono borse e calzature in questa estate minimalista.",en:"The hat is back as key piece and fringe invades bags and footwear in this minimalist summer.",fr:"Le chapeau revient en pièce maîtresse et les franges envahissent sacs et chaussures cet été minimaliste.",de:"Der Hut kehrt als Schlüsselstück zurück und Fransen übernehmen Taschen und Schuhe in diesem minimalistischen Sommer.",es:"El sombrero vuelve como pieza clave y los flecos invaden bolsos y calzado en este verano minimalista."}}
   ]},
   {key:"eventos",icon:"🎫",title:{pt:"Eventos",it:"Eventi",en:"Events",fr:"Evenements",de:"Events",es:"Eventos"},items:[
     {url:"https://www.espn.com/soccer/story/_/id/49162646/world-cup-2026-today-blog-24-06-2026-live-updates-news-fixtures-schedule-results-england-ghana-draw-scotland",img:"https://images.unsplash.com/photo-1522778119026-d647f0596c20?w=600&q=70",src:"ESPN",
      t:{pt:"Copa do Mundo 2026: quatro jogos hoje fecham a rodada da fase de grupos",it:"Mondiali 2026: quattro partite oggi chiudono il turno della fase a gironi",en:"World Cup 2026: four matches today close the group-stage round",fr:"Coupe du Monde 2026: quatre matchs aujourd hui ferment la phase de groupes",de:"WM 2026: Vier Spiele heute schließen die Gruppenphase ab",es:"Mundial 2026: cuatro partidos hoy cierran la jornada de fase de grupos"},
      s:{pt:"Além de Brasil x Escócia, jogam hoje Suíça-Canadá, Marrocos-Haiti e Tchéquia-México.",it:"Oltre a Brasile-Scozia, si giocano oggi Svizzera-Canada, Marocco-Haiti e Cechia-Messico.",en:"Besides Brazil-Scotland: Switzerland-Canada, Morocco-Haiti and Czechia-Mexico all on today.",fr:"Avec Brésil-Écosse: aussi Suisse-Canada, Maroc-Haïti, Tchéquie-Mexique aujourd hui.",de:"Neben Brasilien-Schottland: Schweiz-Kanada, Marokko-Haiti, Tschechien-Mexiko heute.",es:"Además de Brasil-Escocia: Suiza-Canadá, Marruecos-Haití, Chequia-México también hoy."}},
     {url:"https://timesbrasil.com.br/entretenimento/junho-2026-confira-os-principais-shows-e-festivais-em-sao-paulo/",img:"https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?w=600&q=70",src:"Times Brasil",
      t:{pt:"Festas Juninas: Nordeste vibra com Campina Grande, Caruaru e Mossoró em junho",it:"Festas Juninas: il Nordeste vibra con Campina Grande, Caruaru e Mossoró a giugno",en:"Festas Juninas: Northeast Brazil buzzes with Campina Grande, Caruaru and Mossoró",fr:"Festas Juninas: le Nordeste vibre avec Campina Grande, Caruaru et Mossoró en juin",de:"Festas Juninas: Nordeste Brasiliens bebt mit Campina Grande, Caruaru und Mossoró",es:"Festas Juninas: el Nordeste vibra con Campina Grande, Caruaru y Mossoró en junio"},
      s:{pt:"As maiores festas juninas do mundo acontecem agora no Brasil, com shows, quadrilhas e culinária típica.",it:"Le più grandi feste juninas del mondo si svolgono ora in Brasile, con spettacoli, quadrilhas e cucina tipica.",en:"The world biggest Festa Junina celebrations happening now in Brazil with shows, folk dances and traditional food.",fr:"Les plus grandes Festas Juninas du monde se déroulent maintenant au Brésil avec spectacles et gastronomie.",de:"Die größten Festa Junina-Feiern der Welt finden jetzt in Brasilien statt mit Shows, Tänzen und Küche.",es:"Las mayores Festas Juninas del mundo ocurren ahora en Brasil con shows, cuadrillas y gastronomía típica."}}
   ]}
  ]
};
if(window.render){try{window.D=window.ANT_DATA;render();}catch(e){}}
